name: Generate CSS

on:
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
      - name: NPM Instal;
        run: npm ci
      - name: Generate CSS
        run: npm run css-generate
  
